dist: trusty

language: minimal

branches:
  only:
    - master

notifications:
  email: false

env:
  global:
    # Doctr deploy key for benvial/pytheas
    - secure: "TYrr93kJk/7VfPglkfdh/dV4HGachKPfPq8Q3ulkV/2kBczNR396uruBElPG1clbvKs7JVKQZjmGcjqEsXBN5wkELuaeZ4szWszbiiLt3GWVwXGSgVoN3yK/DauI7y4bqDPsrqbCm5zvRhYGlSW+HiV/skjZrrlPj5LrmViNSkZdz9TyhSiK3gq1hvuxU0/odYZQ8w2CGJwFhH+QYS1OrI17FAMv7mxFF3ImEFkWLZJiNprKltZG3btiFWOOLrFOxjCfo3U78ifLJspw0fqPzpulYnwzVZj8cGMrLzv3pUEG0A//3kTy+0k5PZ8/yUqtZAzYCVHjgzduAH2F0Ip6BLo8qNYVvHh728gP9x5rSbyWvoO5u6gKAiKl36b0quqkBtMjHOWwEhsm0Sb72Hi4O6OyBgN2KqWWKbanYXPtfwUpksyTshJXOpOM7K8G9Ffld6yeHwgC+lMN4jfl92OWwpDSgH0Mc7EUaOrnP/2vexdIUm5DRlrYprzdaqyPMI9syy2HuGftGlJgMJuYF0UqVBPgW0tJU/qD5OAwMnmKJlFv6/llHRakRoQ9847bVcwXM/ZDpeZOYBS+yvYJ3bvZdNxkM1QkMyQidQwo4F7K2JGeHEjTYO2Q7FqycUyxAgNzTf7/Sgu2VTJwmxV0jAVFEftm2trZjfEKHh2L2nE4d8I="


install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q --all
  - conda info -a
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes -n testenv cython swig pytest pytest-cov tectonic nlopt
  # - while read requirement; do conda install --yes -n testenv $requirement; done < requirements.txt
  - pip install -r requirements.txt
  - pip install -e .
  - make onelab


script: #run tests
  - pytest -s ./tests --cov

after_success: #make the doc and push to gh-pages the run code coverage analysis
  - set -e
  - pip install doctr sphinx sphinx_bootstrap_theme sphinx_gallery Pillow codecov codacy-coverage
  - cd docs
  - make html
  - make latex
  - tectonic --version
  - tectonic ./_build/latex/pytheas.tex
  - mv ./_build/latex/pytheas.pdf ./_build/html/_downloads/pytheas.pdf
  - cd ..
  - doctr deploy . --built-docs docs/_build/html
  - codecov
  - export CODACY_PROJECT_TOKEN=50a1d9ea26e241f7bfc27117f783e4c0
  - coverage xml
  - python-codacy-coverage -r coverage.xml
