language: python

python:
  - "3.6"
  
branches:
  only:
    - master

notifications:
  email: false
  
env:
  global:
    # Doctr deploy key for benvial/pytheas
    - secure: "TYrr93kJk/7VfPglkfdh/dV4HGachKPfPq8Q3ulkV/2kBczNR396uruBElPG1clbvKs7JVKQZjmGcjqEsXBN5wkELuaeZ4szWszbiiLt3GWVwXGSgVoN3yK/DauI7y4bqDPsrqbCm5zvRhYGlSW+HiV/skjZrrlPj5LrmViNSkZdz9TyhSiK3gq1hvuxU0/odYZQ8w2CGJwFhH+QYS1OrI17FAMv7mxFF3ImEFkWLZJiNprKltZG3btiFWOOLrFOxjCfo3U78ifLJspw0fqPzpulYnwzVZj8cGMrLzv3pUEG0A//3kTy+0k5PZ8/yUqtZAzYCVHjgzduAH2F0Ip6BLo8qNYVvHh728gP9x5rSbyWvoO5u6gKAiKl36b0quqkBtMjHOWwEhsm0Sb72Hi4O6OyBgN2KqWWKbanYXPtfwUpksyTshJXOpOM7K8G9Ffld6yeHwgC+lMN4jfl92OWwpDSgH0Mc7EUaOrnP/2vexdIUm5DRlrYprzdaqyPMI9syy2HuGftGlJgMJuYF0UqVBPgW0tJU/qD5OAwMnmKJlFv6/llHRakRoQ9847bVcwXM/ZDpeZOYBS+yvYJ3bvZdNxkM1QkMyQidQwo4F7K2JGeHEjTYO2Q7FqycUyxAgNzTf7/Sgu2VTJwmxV0jAVFEftm2trZjfEKHh2L2nE4d8I="


install:
  # - sudo apt-get update
  # - pip uninstall --yes numpy
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes -n testenv cython swig pytest
  # - while read requirement; do conda install --yes -n testenv $requirement; done < requirements.txt
  # - python setup.py install
  - pip install -r requirements.txt 
  - pip install sphinx sphinx_bootstrap_theme sphinx_gallery
  - pip install -e .
  - mkdir $TRAVIS_BUILD_DIR/opt
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/opt/bin
  - ./install_onelab_prebuilt.sh
  - ./install_nlopt.sh
  - export TRAVIS_PYTHON_MAJOR_VERSION=${TRAVIS_PYTHON_VERSION:0:3}
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/opt/lib:LD_LIBRARY_PATH
  - export PYTHONPATH=$TRAVIS_BUILD_DIR/opt/lib/python$TRAVIS_PYTHON_MAJOR_VERSION/site-packages:PYTHONPATH

script:
  - pytest
  - set -e
  - pip install doctr
  - cd docs
  - make html
  - cd ..
  - doctr deploy . --built-docs docs/_build/html
