language: python
python:
  - "3.6"
before_install:
  - ./install_onelab_prebuilt.sh
  - ./install_nlopt.sh
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
before_script:
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/bin
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/lib
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/lib/$TRAVIS_PYTHON_VERSION/site-packages
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
