
matrix:
  include:
  - os: linux
    dist: trusty
    env: 
      MINICONDA=Miniconda3-latest-Linux-x86_64.sh
  - os: osx
    env: 
      MINICONDA=Miniconda3-latest-MacOSX-x86_64.sh
      DYLD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/pytheas/tools/bin:$DYLD_LIBRARY_PATH

language: minimal

branches:
  only:
    - master

notifications:
  email: false

env:
  global:
    # Doctr deploy key for benvial/pytheas
    - secure: "TYrr93kJk/7VfPglkfdh/dV4HGachKPfPq8Q3ulkV/2kBczNR396uruBElPG1clbvKs7JVKQZjmGcjqEsXBN5wkELuaeZ4szWszbiiLt3GWVwXGSgVoN3yK/DauI7y4bqDPsrqbCm5zvRhYGlSW+HiV/skjZrrlPj5LrmViNSkZdz9TyhSiK3gq1hvuxU0/odYZQ8w2CGJwFhH+QYS1OrI17FAMv7mxFF3ImEFkWLZJiNprKltZG3btiFWOOLrFOxjCfo3U78ifLJspw0fqPzpulYnwzVZj8cGMrLzv3pUEG0A//3kTy+0k5PZ8/yUqtZAzYCVHjgzduAH2F0Ip6BLo8qNYVvHh728gP9x5rSbyWvoO5u6gKAiKl36b0quqkBtMjHOWwEhsm0Sb72Hi4O6OyBgN2KqWWKbanYXPtfwUpksyTshJXOpOM7K8G9Ffld6yeHwgC+lMN4jfl92OWwpDSgH0Mc7EUaOrnP/2vexdIUm5DRlrYprzdaqyPMI9syy2HuGftGlJgMJuYF0UqVBPgW0tJU/qD5OAwMnmKJlFv6/llHRakRoQ9847bVcwXM/ZDpeZOYBS+yvYJ3bvZdNxkM1QkMyQidQwo4F7K2JGeHEjTYO2Q7FqycUyxAgNzTf7/Sgu2VTJwmxV0jAVFEftm2trZjfEKHh2L2nE4d8I="
    - PATH=$HOME/miniconda/bin:$TRAVIS_BUILD_DIR/pytheas/tools/bin:$PATH

install: #install miniconda, create test environment, install package dependencies
  - echo $PATH
  - make pyinstall
  - make onelab-$TRAVIS_OS_NAME

  
script: #run tests
  - make test

after_success: #make the doc and push to gh-pages the run code coverage analysis
  - make post
