


matrix:
  include:
  - os: linux
    dist: xenial
    env:
      MINICONDA=Miniconda3-latest-Linux-x86_64.sh
  - os: osx
    env:
      MINICONDA=Miniconda3-latest-MacOSX-x86_64.sh
      DYLD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/pytheas/tools/bin:$DYLD_LIBRARY_PATH
  # - os: windows
  #   env:
  #     MINICONDA=Miniconda3-latest-Windows-x86_64.exe

language: sh
filter_secrets: false
branches:
  only:
    - master

notifications:
  email: false

env:
  global:
    # Doctr deploy key for benvial/pytheas
    - secure: "Si/YzpbgkV8p2t2w6D/L0dtSJKVjptWiedXwc7r2mNIbXdI71sIqRmIf6u1UUngyTxGJskkP48LcTBDldUSTAyDJEgr0Isx7ZSvCCqNWyHF4aD8CHS25RrT3vPgf+A/1fE+4c+0M2tmd8Et+9mfyMd4JTGK/o3gryP3fopOLhi0+DZl3QUPgQl03ycYalCGl//5XFhYuNZd5jecu5DI9Za/CGRh2WiJROQTxNlR7SjZdRA2TX/Nph3a5brSA6K7RJc70xlZ9YIGEqjyObYyzZN4WrhlE9W1nTBTGhe2yfTF5yO4U5uBRQ3ZaJz1sAvj0a6DUJVLgJSe3nygEJkPPoVspYAOrUcz4SjSSlQbVV3jEqcA/bKhnivRj98EPVzMOM3aFpKWiwZj3DjFeTm/XInwtRxiy0y7XQ4v/QqJ929F+3MQSSUkdMG4rIlCnWUDPANAk6sFA2/9+HY9lhN31BREWsFWH2yRTalmVH8YdSFoakUpB7c+Q1dunKBz1MsgKpkYHOq8MfEKRc/xS/sGN1iJjgi7EelGNx/JZd18pFy0DDEGDnR3qGSj5z+QP5+/wcs2A/vF/2GVmlF5Zn5bIT7nKKRjAG0RHbPtZD3IwQd+XB2BV4r73rh+/qKkNsuJLExWG6BqguYHb+/xBi3sVb2s7xfIEjs4AmsouXZz5HgE="
    - PATH=$HOME/miniconda/bin:$TRAVIS_BUILD_DIR/pytheas/tools/bin:$PATH

install: #install miniconda, create test environment, install package dependencies
  - make pyinstall
  - make onelab-$TRAVIS_OS_NAME


script: #run tests
  - source activate testenv
  - pytest ./tests -s --cov=./

after_success: #make the doc and push to gh-pages the run code coverage analysis
  - make post
